version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432

  TechChallengeApp_backend:
    image: servian/techchallengeapp:latest
    volumes:
      - ./conf.toml:/TechChallengeApp/conf.toml
    command: "updatedb"
    depends_on:
      - postgres

  TechChallengeApp:
    image: servian/techchallengeapp:latest
    volumes:
      - ./conf.toml:/TechChallengeApp/conf.toml
    ports:
      - 3000:3000
    command: "serve"
    depends_on:
      - TechChallengeApp_backend
